version: '2.0'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "80:80"
        links:
            - php-fpm
    node:
        image: node:8.6-alpine
        volumes:
            - ./:/var/www
        working_dir: /var/www
        tty: true
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
             - ./:/var/www
             - ./docker/php:/usr/local/etc/php/conf.d/
        links:
            - mysql
            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
    mysql:
        image: mysql:8.0
        volumes:
            - ./trash/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "33061:3306"
    redis:
        image: redis:3.0
        ports:
            - "6379:6379"
